### PR TITLE
made drop down country list alphabetical

### PR DESCRIPTION
**Pull request by zackarno**
I found it easier to quickly select countries from drop down if they were alphabetical. I modified the code to sort them and then keep USA as the default selected country (same as before)

### CODE REVIEW

**Review by benflips — CHANGES_REQUESTED** [review]
HI Zack, 

I think you're right.  Made sense to sort countries by number of cases in the beginning.  Makes less sense now.  Line 59 of getDataNew sorts by n cases, and i'm pretty sure you need to sort the whole dataframe rather than just menu names, else labels end up being dissociated from countries in the growth and cfi plots.  Can you pls check?  Can just sort the whole dataframe by country name, probably.

**Comment by zackarno** [comment]
Hi Ben,

The labels didn't seem to disassociate from the plots the way it was sorted. However, it does seem better to sort the whole dataframe as you suggested in case it could cause issues somewhere later in the code. Therefore I just commented out the code where you sort by active cases which leaves you with the dataframe sorted alphabetically.

**Comment by benflips** [comment]
Thanks Zack.

**Comment by benflips** [comment]
Thanks Zack

**Pull request merged**
